# Compile model. 

import os, glob 

# Compline the Fortran Code
fort_env = Environment(ENV = {'PATH':os.environ['PATH']})
fort_env.Append(FLAGS = ['-fno-leading-underscore','-fno-second-underscore'])

fortranSources = glob.glob('Brasse/*.f')
fortranSources += glob.glob('Keppel/*.f')
fortranSources += glob.glob('Bosted/*.f')
fort_env.SharedLibrary('libFortranModel',fortranSources)

# Compile the C++ Code
env = Environment(ENV = {'PATH':os.environ['PATH']})
env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g','-lgfortran'])
env.Append(CPPPATH = ['.'], LIBPATH = ['.'],LIBS = ['FortranModel'])

sources  = glob.glob('testModel.cxx')
env.Program('testModel',sources)


