import os, glob

exeEnv = Environment(ENV = {'PATH':os.environ['PATH']}, h22libs=os.environ['h22libs'])
exeEnv.ParseConfig("root-config --glibs --cflags")
exeEnv.Append(CFLAGS = ['-g'])
exeEnv.Append(CPPPATH = ['$h22libs/include/'], LIBPATH = ['$h22libs/lib/'],LIBS = ['h22','FortranModel','CppModel'])
#exeEnv.Append(LIBPATH = ['/apps/gcc/4.8.2/lib64/'],LIBS = ['quadmath','gfortran'])
exeEnv.Append(CPPPATH = ['$ROOTSYS/include/'], LIBPATH = ['$ROOTSYS/lib/'],LIBS = ['TreePlayer'])
#exeEnv.Append(CPPPATH = ['$h22libs/include/'], LIBPATH = ['$h22libs/lib/'],LIBS = ['FortranModel'])
#exeEnv.Append(CPPPATH = ['$h22libs/include/'], LIBPATH = ['$h22libs/lib/'],LIBS = ['CppModel'])

sources = glob.glob('src/*.cxx')

for target in sources:
    exeEnv.Program(target)

#exeEnv.Program('src/fillHistograms.cxx')
