import os, glob

env = Environment(ENV = {'PATH':os.environ['PATH']})

env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g'])
env.Append(CPPPATH = ['$h22lib/include/'], LIBPATH = ['$h22lib/lib/'],LIBS = ['h22'])

sources = glob.glob('*.cxx')

for prog in sources:
    env.Program(prog)
