# Compile libraries for analysis classes. 

import os, glob 

# Compline the Fortran Code
fort_env = Environment(ENV = {'PATH':os.environ['PATH']}, FORTRAN='gcc', F77COM='gcc') 
fort_env.Append(F77FLAGS = ['-fno-leading-underscore','-fno-second-underscore','-std=legacy'])
fort_env.Append(F77COM = '/usr/bin/gcc' )	
fort_env.SharedLibrary('libelas','elastic.f77')

# Compile the C++ Code 
env = Environment(ENV = {'PATH':os.environ['PATH']})
env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g','-lgfortran'])
env.Append(CPPPATH = ['.'], LIBPATH = ['.'],LIBS = ['libelas'])

#sources  = glob.glob('*.cc')
#env.SharedLibrary('CPP_F1F209',sources)
